/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    noticias: Noticia;
    paginas: Pagina;
    documentos: Documento;
    'links-uteis': LinksUtei;
    banners: Banner;
    manifestacoes: Manifestacoe;
    faq: Faq;
    'acompanhamento-materia': AcompanhamentoMateria;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    paginas: PaginasSelect<false> | PaginasSelect<true>;
    documentos: DocumentosSelect<false> | DocumentosSelect<true>;
    'links-uteis': LinksUteisSelect<false> | LinksUteisSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    manifestacoes: ManifestacoesSelect<false> | ManifestacoesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    'acompanhamento-materia': AcompanhamentoMateriaSelect<false> | AcompanhamentoMateriaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    configuracoes: Configuracoe;
  };
  globalsSelect: {
    configuracoes: ConfiguracoesSelect<false> | ConfiguracoesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  titulo: string;
  /**
   * Gerado automaticamente a partir de "titulo". Edite apenas se necessário.
   */
  slug?: string | null;
  /**
   * Chamada curta exibida nas listagens.
   */
  resumo?: string | null;
  corpo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Imagem principal exibida no card e no topo da notícia.
   */
  foto?: (number | null) | Media;
  categoria?: ('sessoes' | 'projetos' | 'comunicados' | 'eventos' | 'geral') | null;
  data: string;
  /**
   * Marque para exibir no site público.
   */
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: number;
  titulo: string;
  /**
   * Gerado automaticamente a partir de "titulo". Edite apenas se necessário.
   */
  slug?: string | null;
  menuGrupo?:
    | ('' | 'institucional' | 'integrantes' | 'atividade' | 'legislacao' | 'transparencia' | 'atendimento')
    | null;
  /**
   * Se vazio, usa o título da página.
   */
  menuLabel?: string | null;
  menuDesc?: string | null;
  menuIcone?:
    | (
        | 'documento'
        | 'arquivo'
        | 'calendario'
        | 'pessoas'
        | 'lista'
        | 'predio'
        | 'predio2'
        | 'livro'
        | 'megafone'
        | 'balao'
      )
    | null;
  conteudo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos".
 */
export interface Documento {
  id: number;
  titulo: string;
  categoria: 'institucional' | 'regimento' | 'atas' | 'contratos' | 'outros';
  arquivo: number | Media;
  /**
   * Aparece abaixo do título na listagem.
   */
  descricao?: string | null;
  /**
   * Data de aprovação ou publicação.
   */
  dataDocumento?: string | null;
  destaque?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links-uteis".
 */
export interface LinksUtei {
  id: number;
  titulo: string;
  url: string;
  /**
   * Uma linha descrevendo o destino do link.
   */
  descricao?: string | null;
  categoria?: ('geral' | 'municipal' | 'estadual' | 'federal' | 'legislacao' | 'transparencia' | 'parceiros') | null;
  ordem?: number | null;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  /**
   * Identificação interna do banner.
   */
  titulo: string;
  imagem: number | Media;
  /**
   * URL de destino ao clicar.
   */
  link?: string | null;
  /**
   * Ordem no carrossel.
   */
  ordem?: number | null;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifestacoes".
 */
export interface Manifestacoe {
  id: number;
  protocolo?: string | null;
  tipo: 'esic' | 'ouvidoria';
  categoria?: ('reclamacao' | 'denuncia' | 'sugestao' | 'elogio' | 'solicitacao' | 'informacao') | null;
  solicitanteTipo?: ('fisica' | 'juridica') | null;
  formaResposta?: ('email' | 'presencial' | 'correio') | null;
  status?: ('recebido' | 'andamento' | 'respondido') | null;
  nome: string;
  /**
   * Opcional.
   */
  documento?: string | null;
  email: string;
  /**
   * Opcional.
   */
  telefone?: string | null;
  assunto: string;
  mensagem: string;
  /**
   * Resposta oficial enviada ao cidadão.
   */
  resposta?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  pergunta: string;
  resposta?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cidadãos inscritos para receber alertas de tramitação de matérias.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "acompanhamento-materia".
 */
export interface AcompanhamentoMateria {
  id: number;
  email: string;
  /**
   * Identificador numérico da matéria legislativa no SAPL.
   */
  materiaId: number;
  /**
   * Preenchido automaticamente na inscrição (ex.: "PL 12/2025 — Ementa…").
   */
  materiaLabel?: string | null;
  /**
   * Controle interno do cron. Não editar.
   */
  ultimaTramitacaoId?: number | null;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'paginas';
        value: number | Pagina;
      } | null)
    | ({
        relationTo: 'documentos';
        value: number | Documento;
      } | null)
    | ({
        relationTo: 'links-uteis';
        value: number | LinksUtei;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'manifestacoes';
        value: number | Manifestacoe;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'acompanhamento-materia';
        value: number | AcompanhamentoMateria;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  resumo?: T;
  corpo?: T;
  foto?: T;
  categoria?: T;
  data?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  menuGrupo?: T;
  menuLabel?: T;
  menuDesc?: T;
  menuIcone?: T;
  conteudo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos_select".
 */
export interface DocumentosSelect<T extends boolean = true> {
  titulo?: T;
  categoria?: T;
  arquivo?: T;
  descricao?: T;
  dataDocumento?: T;
  destaque?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links-uteis_select".
 */
export interface LinksUteisSelect<T extends boolean = true> {
  titulo?: T;
  url?: T;
  descricao?: T;
  categoria?: T;
  ordem?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  titulo?: T;
  imagem?: T;
  link?: T;
  ordem?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifestacoes_select".
 */
export interface ManifestacoesSelect<T extends boolean = true> {
  protocolo?: T;
  tipo?: T;
  categoria?: T;
  solicitanteTipo?: T;
  formaResposta?: T;
  status?: T;
  nome?: T;
  documento?: T;
  email?: T;
  telefone?: T;
  assunto?: T;
  mensagem?: T;
  resposta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  pergunta?: T;
  resposta?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "acompanhamento-materia_select".
 */
export interface AcompanhamentoMateriaSelect<T extends boolean = true> {
  email?: T;
  materiaId?: T;
  materiaLabel?: T;
  ultimaTramitacaoId?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Identidade do portal: nome, contato, logo e links de transparência.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes".
 */
export interface Configuracoe {
  id: number;
  /**
   * A qual câmara este cadastro pertence (definido no seed). Não editar.
   */
  camaraId?: string | null;
  /**
   * Ex.: Câmara Municipal de Lajeado
   */
  nomeOficial?: string | null;
  /**
   * Ex.: Câmara de Lajeado
   */
  nomeCurto?: string | null;
  /**
   * Letra exibida no bloco da marca.
   */
  inicial?: string | null;
  /**
   * Se vazio, usa a inicial.
   */
  logo?: (number | null) | Media;
  /**
   * Opcional. Aparece atrás do bloco de destaque da home, sob um véu azul que preserva a legibilidade. Se vazio, usa o fundo navy padrão.
   */
  imagemFundo?: (number | null) | Media;
  cidade?: string | null;
  uf?: string | null;
  plenario?: string | null;
  contato?: {
    endereco?: string | null;
    bairro?: string | null;
    telefone?: string | null;
    email?: string | null;
    horario?: string | null;
  };
  redes?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
  };
  /**
   * URLs próprias de cada câmara. Itens vazios não aparecem no menu.
   */
  linksExternos?: {
    transmissaoAoVivo?: string | null;
    licitacoes?: string | null;
    concursos?: string | null;
    diarioOficial?: string | null;
    contasPublicas?: string | null;
  };
  /**
   * Ex.: "● Transmissão ao vivo nas sessões". Se vazio, usa o padrão.
   */
  taglineHero?: string | null;
  /**
   * Se vazio, usa o padrão do portal.
   */
  subtituloHero?: string | null;
  /**
   * Se vazio, usa o padrão.
   */
  textoOuvidoria?: string | null;
  /**
   * Se vazio, usa o padrão.
   */
  textoSIC?: string | null;
  imagemCidadania?: (number | null) | Media;
  imagemMaisAcessados?: (number | null) | Media;
  /**
   * Fotos do plenário exibidas ao lado da agenda.
   */
  galeriaAgenda?:
    | {
        imagem: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Ex.: #081f3d
   */
  corPrimaria?: string | null;
  /**
   * Ex.: #2a6fdb
   */
  corSecundaria?: string | null;
  /**
   * Ex.: #ffce3a
   */
  corDestaque?: string | null;
  /**
   * Ex.: https://camarataquari.rs.gov.br — usada no sitemap e OG tags.
   */
  siteUrl?: string | null;
  /**
   * Até 160 caracteres. Aparece nos resultados de busca quando a página não tem descrição própria.
   */
  descricaoSeo?: string | null;
  /**
   * Ex.: câmara municipal, vereadores, legislação — separadas por vírgula.
   */
  palavrasChave?: string | null;
  /**
   * Setores da Casa, agrupados por nível. Vazio = página não aparece.
   */
  organograma?:
    | {
        setor: string;
        responsavel?: string | null;
        nivel?: ('mesa' | 'diretoria' | 'setor') | null;
        competencias?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * A câmara apenas linka para os sistemas oficiais (ver docs). Agrupados por bloco na página.
   */
  transparenciaLinks?:
    | {
        titulo: string;
        href: string;
        categoria?:
          | ('sistemas' | 'funcionais' | 'despesas' | 'demonstrativos' | 'patrimonio' | 'contratos' | 'dados')
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes_select".
 */
export interface ConfiguracoesSelect<T extends boolean = true> {
  camaraId?: T;
  nomeOficial?: T;
  nomeCurto?: T;
  inicial?: T;
  logo?: T;
  imagemFundo?: T;
  cidade?: T;
  uf?: T;
  plenario?: T;
  contato?:
    | T
    | {
        endereco?: T;
        bairro?: T;
        telefone?: T;
        email?: T;
        horario?: T;
      };
  redes?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
      };
  linksExternos?:
    | T
    | {
        transmissaoAoVivo?: T;
        licitacoes?: T;
        concursos?: T;
        diarioOficial?: T;
        contasPublicas?: T;
      };
  taglineHero?: T;
  subtituloHero?: T;
  textoOuvidoria?: T;
  textoSIC?: T;
  imagemCidadania?: T;
  imagemMaisAcessados?: T;
  galeriaAgenda?:
    | T
    | {
        imagem?: T;
        id?: T;
      };
  corPrimaria?: T;
  corSecundaria?: T;
  corDestaque?: T;
  siteUrl?: T;
  descricaoSeo?: T;
  palavrasChave?: T;
  organograma?:
    | T
    | {
        setor?: T;
        responsavel?: T;
        nivel?: T;
        competencias?: T;
        id?: T;
      };
  transparenciaLinks?:
    | T
    | {
        titulo?: T;
        href?: T;
        categoria?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}